services:
  backend:
    container_name: backend
    profiles:
      - all
      - backend
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    restart: always
    expose:
      - '3001'
  frontend:
    container_name: frontend
    profiles:
      - all
      - frontend
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    restart: always
    ports:
      - "81:80"
